package io.github.mongsil3344.backend.database;

import org.springframework.boot.ApplicationRunner;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.core.Ordered;
import org.springframework.core.annotation.Order;
import org.springframework.jdbc.core.JdbcTemplate;

// 데이터베이스 초기화 설정코드
@Configuration
public class DatabaseInitializer {

    // 아래 두개의 sql문이 서버가 실행될때 실행되며 데이터베이스를 초기화
    // if not exists가 붙어있기때문에 해당 테이블이 존재하면 실행되지 않음
    @Bean
    @Order(Ordered.HIGHEST_PRECEDENCE)
    ApplicationRunner initializeDatabase(JdbcTemplate jdbcTemplate) {
        return args -> {
            jdbcTemplate.execute("""
                    create table if not exists menus (
                        id bigint generated by default as identity primary key,
                        name varchar(100) not null,
                        price integer not null,
                        description varchar(255) not null
                    )
                    """);

            jdbcTemplate.execute("""
                    create table if not exists customer_orders (
                        id bigint generated by default as identity primary key,
                        customer_name varchar(100) not null,
                        total_price integer not null,
                        created_at timestamp not null,
                        order_json clob not null
                    )
                    """);
        };
    }
}
