package io.github.mongsil3344.backend.database;

import org.springframework.boot.ApplicationRunner;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.core.Ordered;
import org.springframework.core.annotation.Order;
import org.springframework.jdbc.core.JdbcTemplate;

@Configuration
public class DatabaseInitializer {

    @Bean
    @Order(Ordered.HIGHEST_PRECEDENCE)
    ApplicationRunner initializeDatabase(JdbcTemplate jdbcTemplate) {
        return args -> {
            jdbcTemplate.execute("""
                    create table if not exists menus (
                        id bigint generated by default as identity primary key,
                        name varchar(100) not null,
                        price integer not null,
                        description varchar(255) not null
                    )
                    """);

            jdbcTemplate.execute("""
                    create table if not exists customer_orders (
                        id bigint generated by default as identity primary key,
                        customer_name varchar(100) not null,
                        total_price integer not null,
                        created_at timestamp not null,
                        order_json clob not null
                    )
                    """);
        };
    }
}
